languageCode = "en-us"
title = "Mitch Roote"
theme = "simple"
sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -100

  [[menu.external]]
    name = "github"
    url = "https://github.com/mroote"
    pre = "<i data-feather='github'></i>"
  [[menu.external]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/mitchroote/"
    pre = "<i data-feather='linkedin'></i>"
  [[menu.external]]
    name = "thingiverse"
    url = "https://www.thingiverse.com/majormjr/designs"
    pre = "<i data-feather='layers'></i>"

  [[menu.about]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.about]]
    name = "Portfolio"
    url = "/about/portfolio/"
    weight = 20
  [[menu.about]]
    name = "Projects"
    url = "/about/projects/"
    weight = 20
  [[menu.about]]
    name = "Tutorials"
    url = "/about/tutorials/"
    weight = 30

[params]
  copyrighthtml = "Â© 2020 Mitch Roote"
